name: Bug Report
description: File a bug report
title: "[Bug/Crash]: "
labels: ["bug"]
assignees:
  - vaporvee
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug/crash report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.2
        - 1.1
        - 1.0
        - Custom build
    validations:
      required: true
  - type: input
    id: gd-version
    attributes:
      label: Godot Version
      description: This addon is ONLY for 4.0 and above!
      placeholder: e.g. 4.0.2-stable
    validations:
      required: true
  - type: textarea
    id: gdscript
    attributes:
      label: GDScript
      description: A place for any GDScript to be formatted
      placeholder: Put in your GDScript code here and make comments with `#` to tell where wich file ends
      render: gdscript
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: If you have anything else tell me here
      placeholder: Anything else.
    validations:
      required: false
  - type: checkboxes
    id: reinstalling
    attributes:
      label: Checks
      description: Common mistakes (Adding more in the future sorry btw)
      options: 
        - label: I tried reinstalling the addon in a new project.
          required: true
